# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = ""
    key          = ""
    region       = "us-east-1"
    role_arn     = ""
    session_name = "srinath.jamboju"
  }
}
